//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLDiem
    {
        public string MaDiem { get; set; }
        public double DiemLab { get; set; }
        public double DiemThi { get; set; }
        public double DiemTongKet { get; set; }
        public string MaSV { get; set; }
        public string MaMonHoc { get; set; }
    
        public virtual QLMonHoc QLMonHoc { get; set; }
        public virtual QLSinhVien QLSinhVien { get; set; }
    }
}
