//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDTEntities : DbContext
    {
        public QLDTEntities()
            : base("name=QLDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QLChuyenNganh> QLChuyenNganhs { get; set; }
        public virtual DbSet<QLDiem> QLDiems { get; set; }
        public virtual DbSet<QLGiangVien> QLGiangViens { get; set; }
        public virtual DbSet<QLHocKy> QLHocKies { get; set; }
        public virtual DbSet<QLLich> QLLiches { get; set; }
        public virtual DbSet<QLLop> QLLops { get; set; }
        public virtual DbSet<QLLopMon> QLLopMons { get; set; }
        public virtual DbSet<QLMonHoc> QLMonHocs { get; set; }
        public virtual DbSet<QLNganh> QLNganhs { get; set; }
        public virtual DbSet<QLPhong> QLPhongs { get; set; }
        public virtual DbSet<QLSinhVien> QLSinhViens { get; set; }
        public virtual DbSet<QLUser> QLUsers { get; set; }
    }
}
