//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLGiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLGiangVien()
        {
            this.QLLopMons = new HashSet<QLLopMon>();
        }
    
        public string MaGV { get; set; }
        public string HoTenGV { get; set; }
        public string GioiTinhGV { get; set; }
        public System.DateTime NgaySinhGV { get; set; }
        public string DiaChiGV { get; set; }
        public string SoDienThoaiGV { get; set; }
        public string EmailGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLLopMon> QLLopMons { get; set; }
    }
}
