//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLLich
    {
        public string MaLichHoc { get; set; }
        public string MaHocKy { get; set; }
        public System.DateTime NgayHoc { get; set; }
        public int GioHoc { get; set; }
        public Nullable<System.DateTime> NgayHoc { get; set; }
        public Nullable<int> GioHoc { get; set; }
    
        public virtual QLHocKy QLHocKy { get; set; }
    }
}
