//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLLopMon
    {
        public string MaLopMon { get; set; }
        public string MaGV { get; set; }
        public string MaMonHoc { get; set; }
        public string MaPhong { get; set; }
        public string MaHocKy { get; set; }
        public string MaLop { get; set; }
    
        public virtual QLGiangVien QLGiangVien { get; set; }
        public virtual QLHocKy QLHocKy { get; set; }
        public virtual QLLop QLLop { get; set; }
        public virtual QLMonHoc QLMonHoc { get; set; }
        public virtual QLPhong QLPhong { get; set; }
    }
}
