//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao_Nhom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLNganh
    {
        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public string MaSV { get; set; }
        public string MaCN { get; set; }
        public string MaLop { get; set; }
    
        public virtual QLChuyenNganh QLChuyenNganh { get; set; }
        public virtual QLLop QLLop { get; set; }
        public virtual QLSinhVien QLSinhVien { get; set; }
    }
}
